### PR TITLE
feat: rebuild the s2e image upon master branch updates

### PR DESCRIPTION
**Pull request by yype**
Merging this PR, the CI will rebuild the s2e image upon master branch updates and automatically push the image to the GTISC registry.

### CODE REVIEW

**Comment by Changochen** [comment]
Make sure the CI can be run correctly.

https://github.com/GTISC/s2e/actions/runs/8503451225/workflow

**Review by Changochen — COMMENTED** [review]
LGTM

**Comment by Changochen** [comment]
image


Please run it manually to see whether it works.

**Comment by yype** [comment]
> image
> 
> Please run it manually to see whether it works.

I just manually tested it on this branch. It should work now.

https://github.com/GTISC/s2e/actions/runs/8509150028/job/23304530409

**Review by Changochen — APPROVED** [review]
LGTM

**Pull request merged**
